### ISSUE TITLE
Nil Pointer Dereference on EVSE Disconnected

### ISSUE THREAD

**Issue by Kr0llx** [enbility/cemd#21]
# Description

When cemd is connected to an EVSE and the EVSE disconnects the following function is called.
https://github.com/enbility/cemd/blob/e18d4265b5ec281a65ed664bec2c67f593cf5a29/ucevsecc/events.go#L57-L59

Here the `entity` is accessed to get the Device however the enitity is nil causing the exception.

**Comment by andig** [comment]
What is the expectation during disconnect? If https://github.com/enbility/cemd/issues/23 gets implemented the disconnecting entity would still be needed at this point.

**Comment by DerAndereAndi** [comment]
Yes, that is a bug. The entity is no longer associated to the Device, as it is disconnected. I will fix it.

**Comment by andig** [comment]
Would it make sense to change the order? I.e. in case of disconnect invoke the callback first and the disassociate the entity from the device? Disclaimer would be that you can‘t use is for any spine messaging but you‘d still have access to the relevant information for just that callback.

**Comment by DerAndereAndi** [comment]
This should now be fixed via https://github.com/enbility/cemd/commit/d46d7436de874166307557b28fa7a8968fb18a74

**Comment by Kr0llx** [comment]
I tried it out but there seems to still be a bug. At the moment e.g. UCEVSECC uses the payload to get the entity:
https://github.com/enbility/cemd/blob/f4fdd6b27e473863bf498234e93b7c45d125a31f/ucevsecc/events.go#L57-L59

however in an disconnect situation. This is not populated as can be seen below.
https://github.com/enbility/spine-go/blob/7fea429a63c1ac23055637265b4c21ddf9c2ad26/spine/device_local.go#L144-L157

I think there the entity needs to be added.

**Comment by DerAndereAndi** [comment]
Right, I forgot to remove this device disconnect check from the EVSE, as device level is handled on the CEM and the use cases only care about entity changes. See https://github.com/enbility/cemd/commit/6ce38e7775b877e2a219b381e839ea59b8cb1f6a

**Comment by Kr0llx** [comment]
Thanks works like a charm now.
