### ISSUE TITLE
UC State of Charge not implementing all measurements

### ISSUE THREAD

**Issue by Kr0llx** [enbility/cemd#22]
As of EEBus UC State of Charge does not only contain the State of Charge but furthermore:
- Nominal Capacity
- State of Health
- Actual Travel Range
However these are not implemented at the moment

**Comment by DerAndereAndi** [comment]
Yes. No car provides this data and the scenarios will soon be removed from EEBUS as well.  Hence it makes no sense to implement them.

**Comment by Kr0llx** [comment]
Understand. Will close this then.
