### ISSUE TITLE
CEM: simplify event handlers

### ISSUE THREAD

**Issue by andig** [enbility/cemd#23]
Creating CEM UCs requires

    type EventHandlerCB func(ski string, device spineapi.DeviceRemoteInterface, entity spineapi.EntityRemoteInterface, event EventType)

Given that `spineapi.EntityRemoteInterface` includes `Device()` it seems the `device` parameter is not necessary? Same should apply to `SKI` via `device`?

**Comment by DerAndereAndi** [comment]
I don't think this is good, as an EV disconnect has to report the Entity that was disconnected. But as the entity is no longer connected, it has lost the relation to the `Device`. So you can't get the SKI any longer that way.

In addition there are messages that don't have an `Entity` set, e.g. if the wallbox was connected or disconnected (offline).

For now I would like to keep it as it is.

**Comment by DerAndereAndi** [comment]
The event handlers have been changed a bit, also based on your suggestions. See https://github.com/enbility/cemd/commit/d46d7436de874166307557b28fa7a8968fb18a74
