### ISSUE TITLE
CEM: differentiate device and entity callbacks

### ISSUE THREAD

**Issue by andig** [enbility/cemd#24]
Currently, Cem and use cases share the same `EventHandlerCB` callback type. Together with https://github.com/enbility/cemd/issues/23 I'd propose to update as follows:

    type DeviceEventCallback func(device spineapi.DeviceRemoteInterface, event EventType)

and

    type EntityEventCallback func(entity spineapi.EntityRemoteInterface, event EventType)

Happy to provide a PR.

**Comment by DerAndereAndi** [comment]
See my argument in the linked ticket. It is not that simple. The SKI has to be there for all events for an entity, it can be argued if separated from the device though.

I'll think about providing different callbacks for the device and entity.

**Comment by DerAndereAndi** [comment]
Different callbacks for device events and entity related events has been implemented in https://github.com/enbility/cemd/commit/d46d7436de874166307557b28fa7a8968fb18a74
