### ISSUE TITLE
call eventCB api.EntityEventCallback in a go func

### ISSUE THREAD

**Issue by DAMEK86** [enbility/cemd#35]
while debugging LPC usecase, i was able to close the underlining websocket if the callback get stuck, e.g. while waiting for a long running task.

example code to reproduce
```
func (s *cem) entityEventCB(ski string, device spineapi.DeviceRemoteInterface, entity spineapi.EntityRemoteInterface, event api.EventType) {
time.Sleep(120 * time.Second)
}

expected behavior:
- callback doesn't affect the spine lib itself

**Comment by DerAndereAndi** [comment]
RIght now the callbacks are not invoked in a thread but synchronously. I am not sure yet if this should stay or be changed right now. So for now, you might want to run your own code in a go routine instead.

**Comment by DerAndereAndi** [comment]
This is now changed in the latest SPINE update: https://github.com/enbility/spine-go/commit/1f18cd7937fe2a569c8ca50df413d8b77f9a4fc4
