### ISSUE TITLE
Add mechanism to forward Heartbeat status for LPC/LPP usecases to CEM

### ISSUE THREAD

**Issue by DAMEK86** [enbility/cemd#38]
Depending on if the Heartbeats are correctly received by a Controlbox for an interval determines different states that the system needs to go into.
Therefor we need to inform the CEM about the current Heartbeat status so the same is able to handle missing heatbeats and inform other entities to go into failsafe state.

**Comment by DerAndereAndi** [comment]
This is implemented in eebus-go repository.
